# Generated by Django 5.2.7 on 2025-10-22 11:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "invoice_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=100)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "balance_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_at", models.DateTimeField()),
                ("days_overdue", models.IntegerField(default=0)),
                ("aging_bucket", models.IntegerField(default=0)),
                ("invoice_at", models.DateTimeField()),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AUTHORIZED", "Authorized"),
                            ("PENDING", "Pending"),
                            ("PAID", "Paid in Full"),
                            ("CANCELLED", "Cancelled"),
                            ("DRAFT", "Draft"),
                            ("VOIDED", "Voided"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PARTIALLY_REFUNDED", "Partially Refunded"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="DRAFT",
                        max_length=50,
                        verbose_name="Invoice Status",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BILL", "Bill"),
                            ("INVOICE", "Invoice"),
                            ("CREDITMEMO", "Credit Memo"),
                        ],
                        default="INVOICE",
                        max_length=50,
                        verbose_name="Invoice Type",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        db_column="customer_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "db_table": "invoices",
                "ordering": ["-created_at"],
            },
        ),
    ]
