# Generated by Django 5.2.7 on 2025-10-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
